### ISSUE TITLE
[FR] Support for subresource integrity

### ISSUE THREAD

**Issue by IAmPicard** [shirotech/webpack-cdn-plugin#38]
See details on [subresource integrity here](https://infosec.mozilla.org/guidelines/web_security#subresource-integrity).

It would be awesome to add this support to webpack-cdn-plugin.

Thank you!

**Comment by van-nguyen** [comment]
Hi @IAmPicard sure that feature looks good to add, assuming this plugin should automatically generate the token correct?

**Comment by IAmPicard** [comment]
> Hi @IAmPicard sure that feature looks good to add, assuming this plugin should automatically generate the token correct?

Yes, ideally the hash would be automatically generated. [This](https://github.com/waysact/webpack-subresource-integrity) may be useful for inspiration. It seems to be using the standard node 'crypto' module (`crypto.createHash(hashFuncName).update(source, "utf8").digest("base64");`).

**Comment by morriq** [comment]
👍

**Comment by miszo** [comment]
👍

**Comment by MartinManev** [comment]
:+1:
