### ISSUE TITLE
Possible bug around namespaced modules.

### ISSUE THREAD

**Issue by Gisleburt** [shirotech/webpack-cdn-plugin#46]
I don't seem to be able to add modules that are namespaced, eg
```javascript
{ name: '@babel/polyfill', var: 'BabelPolyfill', path: `dist/polyfill${prod ? '.min' : ''}.js` },
{ name: '@apolitical/styleguide', var: 'ApoliticalStyleguide', path: 'dist/index.js' },
```
For these I get `ApoliticalStyleguide is not defined` or `BabelPolyfill is not defined`.

Is there something I've missed?

**Comment by morriq** [comment]
Hello,
are you sure that you have defined ApoliticalStyleguide before running your application?

**Comment by levanax** [comment]
I also encountered the same problem.

**Comment by Gisleburt** [comment]
The problem is that the `var` must be defined by the UMD package being imported. 

Frustratingly few people seem to document what the `var` (the global variable their package is exported as) is, but you can usually find it if you can read the unminified code.

One day we'll hopefully have a better JS module system but for now the best thing anyone with this issue can do is encourage the maintainers of packages they're consuming to publish what their package is exported as.
