### ISSUE TITLE
Support for preload, prefetch,  & preconnect attributes for peformance

### ISSUE THREAD

**Issue by Oba-One** [shirotech/webpack-cdn-plugin#56]
Hi! I love your package and have seen my build times drastically reduce. I was wondering if there's support for the preload . and prefetch attributes that help with  performance.

**Comment by konojunya** [comment]
I think that it is a very good idea to put preload attribute in consideration of performance. 
As I think it is important to keep in mind that it is important to be aware of performance, I will make a PR soon so that this can also function as the same option :)

**Comment by konojunya** [comment]
@shirotech plz, close this issue.

**Comment by shirotech** [comment]
As suggested by @konojunya I will be closing this issue, unless otherwise I'm happy to re-open.
