### ISSUE TITLE
not support packages that have a scope

### ISSUE THREAD

**Issue by njzjz** [shirotech/webpack-cdn-plugin#68]
If the package has a scope like `@scope/package-name`, it will generate scripts like
```js
module.exports = @scope/package-name;
```
which will raise errors.

**Comment by shirotech** [comment]
@njzjz thanks for reporting, can you please post that error so we have a reference of it and come up with a possible fix.

**Comment by njzjz** [comment]
The `webpack-cdn-plugin` raises no errors, but the scripts it generates should be 
```js
module.exports = "@scope/package-name";
```
It is wrong if it does not has `"`.

**Comment by njzjz** [comment]
Oh I see, I can manually assign the name.
