### ISSUE TITLE
comcompatibleWith html-webpack-plugin@4.0.0-beta.x

### ISSUE THREAD

**Issue by yu-cover** [shirotech/webpack-cdn-plugin#69]
html-webpack-plugin@4.0.0-beta.x has no htmlWebpackPluginBeforeHtmlGeneration hook
https://github.com/jantimon/html-webpack-plugin#events

**Comment by shirotech** [comment]
I think we can support it once it's out of beta, please remind me to re-open this when it does. Thanks @yu-cover
